# hero.py
HERO_SPEED = 5
HERO_HEALTH = 3
HERO_INVULNERABLE_TIME = 120

# Enemy settings
ENEMY_COUNT = 5
ENEMY_SPEED = 2

# Block dimensions
TILE_SIZE = 64
BACKGROUND_WIDTH = 256

# Window dimensions
WIDTH = 1200
HEIGHT = 800

GRAVITY = 1
JUMP_STRENGTH = 25
GROUND_Y = HEIGHT - TILE_SIZE
GROUND_Y_CHARACTER = GROUND_Y - 114